version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventory_management_db
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  product-service:
    build:
      context: ./product-service
    command: uvicorn app:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./product-service/app:/app
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=inventory_management_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - RABBITMQ_HOST=rabbitmq
    networks:
      - app-network
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8001:8001"

  stock-service:
    build:
      context: ./stock-service
    command: uvicorn app:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./stock-service/app:/app
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=inventory_management_db
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - RABBITMQ_HOST=rabbitmq
    networks:
      - app-network
    depends_on:
      - db
      - rabbitmq
    ports:
      - "8002:8002"

  gateway-service:
    build:
      context: ./gateway-service
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./gateway-service/app:/app
    networks:
      - app-network
    depends_on:
      - product-service
      - stock-service
    ports:
      - "8000:8000"

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
