version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventory_management_db
    networks:
      - app-service
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  product-service:
    build:
      context: ./product-service
    command: uvicorn app.app:app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - ./product-service/app:/app
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventory_management_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "8001:8001"

  stock-service:
    build:
      context: ./stock-service
    container_name: stock-service
    command: uvicorn app.app:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./stock-service/app:/app
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventory_management_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    networks:
      - app-network
    depends_on:
      - db
    ports:
      - "8002:8002"

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    command: uvicorn app.app:app --host 0.0.0.0 --port 8002 --reload
    volumes:
      - ./gateway-service/app:/app
    ports:
      - "8000:8000"
    depends_on:
      - product-service
      - stock-service
    networks:
      - app-network

  networks:
    app-netwok:
      driver: bridge

  volumes:
    db_data:
