version: '3.9'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventory_management_db
    ports:
      - "5432:5432"

  product-service:
    build:
      context: ./product-service
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./product-service:/app
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: inventory_management_db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    depends_on:
      - db
    ports:
      - "8000:8000"
